name: ToxiUI Stable Build Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  on-development-branch-check:
    runs-on: ubuntu-latest
    outputs:
      on_development: ${{ env.on_development }}
    steps:
      - name: Fix path for checkout
        run: git config --global remote.origin.followRemoteHEAD never
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: rickstaa/action-contains-tag@v1.2.10
        id: contains_tag
        with:
          frail: false
          reference: "development"
          tag: "${{ github.ref }}"
      - name: Set output for on_development
        run: echo "on_development=${{ steps.contains_tag.outputs.retval }}" >> $GITHUB_ENV

  publish-stable-release:
    runs-on: ubuntu-latest
    needs: [on-development-branch-check]
    if: ${{ needs.on-development-branch-check.outputs.on_development == 'true' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Draft release and upload release
        uses: Toxicom/packager@master
        if: success()
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_TOKEN }}
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
        with:
          args: -m .pkgmeta
      - name: Read release tag
        if: success()
        id: vars
        run: |
          echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Announce new stable release on Discord
        uses: sarisia/actions-status-discord@f268209d088ace9f9666322b04d60e013fef212d
        if: success()
        with:
          webhook: ${{ secrets.WEBHOOK_URL }}
          title: ":star: New stable build of ToxiUI is ready! :star:"
          nodetail: true
          color: 0x18a8ff
          username: ToxiBot - Stable Release
          avatar_url: "https://i.imgur.com/ib1CSUx.png"
          description: |
            :tools: Release `${{ env.tag }}`
            :scroll: Changelog in game with the `/tx changelog` command!

            :hearts: Thank you all for getting this release ready! :hearts:

            :floppy_disk: Download soon:tm: on CurseForge, Wago or WoWInterface
            :information_source: Best way to manage your AddOns is via https://wowup.io
      - name: Upload release file to Discord
        uses: nocturlab/upload-to-discord@master
        if: success()
        env:
          DISCORD_WEBHOOK: ${{ secrets.WEBHOOK_URL }}
        with:
          args: .release/*.zip
          username: ToxiBot - Stable Release
          avatar_url: "https://i.imgur.com/ib1CSUx.png"
